title: "" # name of the site
author: "" # name of site's author
email: hydnwc@gmail.com # email of site's author
url: haydencooper.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  <b>Hayden Cooper</b> <br>
  Software Engineer <br>
  Based in Australia <br> <br>
   
  <a href="https://haydenwc.dev">GitHub</a> <br>
  <a href="https://linkedin.com/in/haydenwc">LinkedIn</a> <br>
  <a href="mailto:me@haydenc.dev">Email</a> <br>
  <a href="recipes.html">Recipes</a> <br>
  <a href="resume.html">Resume</a> <br>
  <a href="archive.html">Blog</a> 

permalink: /:slug.html

favicon: "" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%m-%d-%Y" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
