title: "Hayden Cooper" # name of the site
author: "" # name of site's author
email: hydnwc@gmail.com # email of site's author
url: haydencooper.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  <div id="hayden"><b>Hayden Cooper</b></div><br>
  Enamoured with <span class="beauty">beauty in simplicity.</span> Aspiring to build wholeheartedly, embrace unknowns and approach engineering with childlike curiosity. 
  <br> <br>
  Engineering Intern @ <a href="https://atlassian.com">Atlassian</a>
  
 

permalink: /:slug.html

favicon: "" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "Back" # customize text for homepage link in post layout
  date_format: "%-d %B, %Y     " # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
